version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: crd-installer
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          image: "quay.io/giantswarm/crd-installer"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
