version: 2.1

orbs:
  architect: giantswarm/architect@2.7.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: crd-installer
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-crd-installer-to-docker
          image: "docker.io/giantswarm/crd-installer"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-crd-installer-to-quay
          image: "quay.io/giantswarm/crd-installer"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
